services:
  streambot:
    image: stevenedwards/streambot:latest
    container_name: streambot
    ports:
      - "3123:3000"
    stdin_open: true  
    tty: true        
    devices:
      - /dev/dri:/dev/dri
    privileged: true  
    environment:
        DISCORD_TOKEN: ""
        #Optional Variables
        HARDWARE_ACCELERATION: "true"
        FPS: 30
        WIDTH: 1920
        HEIGHT: 1080
        BITRATE_KBPS: 3000
        MAX_BITRATE_KBPS: 5000
        H26X_PRESET: "medium"
        READ_AT_NATIVE_FPS: "true"