services:
  streambot:
    image: stevenedwards/streambot:latest
    container_name: streambot
    ports:
      - "3123:3123"
    stdin_open: true  
    tty: true        
    devices:
      - /dev/dri:/dev/dri
    privileged: true  
    environment:
        DISCORD_TOKEN: ""
        # Optional Variables (will override any defaults and variables passed in API call)
        FPS: ""
        MAX_FPS: ""
        WIDTH: ""
        HEIGHT: ""
        BITRATE_KBPS: ""
        MAX_BITRATE_KBPS: ""
        H26X_PRESET: ""
        HARDWARE_ACCELERATION: ""
        READ_AT_NATIVE_FPS: ""
        RTCP_SENDER: ""
        MINIMIZE_LATENCY: ""
        FORCE_CHACHA: ""